version: '3.8'

services:
  app:
    image: php:8.2-apache
    platform: linux/amd64
    container_name: php_app
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:5.7
    platform: linux/amd64
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_DATABASE: basedados_pap
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    platform: linux/amd64
    container_name: phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    depends_on:
      - db

volumes:
  db_data: